[program:edm-backup-resume]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-backup-resume.sh
autostart=false
autorestart=false
startsecs=0
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=300
stdout_logfile=/var/log/portal/edm-backup-resume.log
redirect_stderr=true
stdout_logfile_maxbytes=0
