[program:edm-validate-tensors]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-validate-tensors.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/var/log/portal/edm-validate-tensors.log
redirect_stderr=true
stdout_logfile_maxbytes=0
