[program:edm-v2-score-r48-corrected]
environment=PROC_NAME="%(program_name)s"
command=/workspace/melodic_edm_training_pipeline/server/supervisor/edm-v2-score-r48-corrected.sh
directory=/workspace/melodic_edm_training_pipeline
autostart=false
autorestart=false
startsecs=0
stdout_logfile=/workspace/melodic_edm_training_pipeline/logs/v2-score-r48-corrected.log
redirect_stderr=true
stdout_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
