[program:edm-separate-vocals-1]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-separate-vocals-1.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/var/log/portal/edm-separate-vocals-1.log
redirect_stderr=true
stdout_logfile_maxbytes=0
