[program:edm-v2-evaluate-enhanced]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-v2-evaluate-enhanced.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=180
stdout_logfile=/var/log/portal/edm-v2-evaluate-enhanced.log
redirect_stderr=true
stdout_logfile_maxbytes=0
