[program:edm-v2-upload-audio-dataset]
command=/bin/bash /workspace/melodic_edm_training_pipeline/server/supervisor/edm-v2-upload-audio-dataset.sh
directory=/workspace/melodic_edm_training_pipeline
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true
stopwaitsecs=300
stdout_logfile=/var/log/portal/edm-v2-upload-audio-dataset.log
redirect_stderr=true
stdout_logfile_maxbytes=0
environment=HOME="/root",PYTHONUNBUFFERED="1"
