[program:edm-v2-preprocess-validation]
environment=PROC_NAME="%(program_name)s",GPU_INDEX="0",DATASET_JSON="data_v2/dataset_validation.json",TENSOR_OUTPUT="data_v2/tensors_validation_raw"
command=/opt/supervisor-scripts/edm-v2-preprocess.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/var/log/portal/edm-v2-preprocess-validation.log
redirect_stderr=true
stdout_logfile_maxbytes=0
