[program:edm-v2-validate-claim-consensus]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-v2-validate-claim-consensus.sh
autostart=false
autorestart=false
startsecs=0
startretries=0
stdout_logfile=/var/log/portal/edm-v2-validate-claim-consensus.log
redirect_stderr=true
stdout_logfile_maxbytes=0
