[program:edm-preprocess-validation]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-preprocess-validation.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/var/log/portal/edm-preprocess-validation.log
redirect_stderr=true
stdout_logfile_maxbytes=0
