[program:edm-find-clean-sections]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-find-clean-sections.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/var/log/portal/edm-find-clean-sections.log
redirect_stderr=true
stdout_logfile_maxbytes=0
