[program:edm-backup-metadata]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-backup-metadata.sh
autostart=false
autorestart=false
startsecs=0
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/var/log/portal/edm-backup-metadata.log
redirect_stderr=true
stdout_logfile_maxbytes=0
