[program:edm-v2-setup-moss]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/edm-v2-setup-moss.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/var/log/portal/edm-v2-setup-moss.log
redirect_stderr=true
stdout_logfile_maxbytes=0
